-- Migration: Image Deploy Status
-- Adds columns to track AI-generated image deployment status

-- Add image deployment tracking columns to posts table
ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_deploy_status VARCHAR(20) DEFAULT 'none';
-- Possible values: 'none', 'generating', 'pending_deploy', 'deployed', 'failed'

ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_commit_sha VARCHAR(64);
-- GitHub commit SHA when image was committed

ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_error TEXT;
-- Error message if image generation/deployment failed

ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_generated_at TIMESTAMP;
-- When the image was generated

-- Index for finding posts by deploy status
CREATE INDEX IF NOT EXISTS idx_posts_image_deploy_status ON posts(image_deploy_status);

-- Update existing posts: if they have an image_filename, mark as deployed (they're already in git)
UPDATE posts
SET image_deploy_status = 'deployed'
WHERE image_filename IS NOT NULL
  AND image_filename != ''
  AND image_deploy_status = 'none';

-- Add comments
COMMENT ON COLUMN posts.image_deploy_status IS 'Tracks image deployment: none, generating, pending_deploy, deployed, failed';
COMMENT ON COLUMN posts.image_commit_sha IS 'GitHub commit SHA when AI-generated image was committed';
COMMENT ON COLUMN posts.image_error IS 'Error message if image generation or deployment failed';
COMMENT ON COLUMN posts.image_generated_at IS 'Timestamp when the image was generated by AI';
