#!/bin/bash

# Rename blog post images to SEO-friendly names based on their titles

mv "CCA-_0000_Layer-54.png" "utah-contractor-insurance-guide-requirements-costs-coverage-2025.png"
mv "CCA-_0001_Layer-53.png" "michigan-contractor-insurance-guide-requirements-costs-coverage-2025.png"
mv "CCA-_0002_Layer-52.png" "arizona-contractor-insurance-guide-complete-coverage-requirements-costs-2024.png"
mv "CCA-_0003_Layer-51.png" "new-jersey-contractor-insurance-guide-requirements-costs-hurricane-coverage-2024.png"
mv "CCA-_0004_Layer-50.png" "minnesota-contractor-insurance-guide-requirements-costs-cold-weather-coverage-2024.png"
mv "CCA-_0005_Layer-49.png" "kentucky-contractor-insurance-guide-requirements-costs-coverage-bluegrass-state-2024.png"
mv "CCA-_0006_Layer-48.png" "kansas-contractor-insurance-guide-requirements-costs-tornado-coverage-2024.png"
mv "CCA-_0007_Layer-47.png" "how-much-general-liability-insurance-roofer-need-california-2024-complete-guide.png"
mv "CCA-_0008_Layer-46.png" "vermont-contractor-insurance-registration-guide-act-250-compliance-opr-requirements-2024.png"
mv "CCA-_0009_Layer-45.png" "commercial-auto-insurance-contractors-complete-2024-guide.png"
mv "CCA-_0010_Layer-44.png" "workers-compensation-insurance-complete-contractor-guide-2024.png"
mv "CCA-_0011_Layer-43.png" "how-insurance-claims-impact-future-premiums-cca.png"
mv "CCA-_0012_Layer-42.png" "why-roofing-contractors-need-commercial-auto-insurance.png"
mv "CCA-_0013_Layer-41.png" "true-cost-skimping-coverage-why-cheap-insurance-costs-more.png"
mv "CCA-_0014_Layer-40.png" "hidden-costs-commercial-auto-insurance-contractors.png"
mv "CCA-_0015_Layer-39.png" "commercial-auto-insurance-basics-contractors.png"
mv "CCA-_0016_Layer-38.png" "roof-coverage-acv-vs-replacement-cost-making-smart-insurance-choices.png"
mv "CCA-_0017_Layer-37.png" "navigating-insurance-renewals-policy-changes-strategic-guide.png"
mv "CCA-_0018_Layer-36.png" "history-workers-compensation-industrial-revolution-modern-protection.png"
mv "CCA-_0019_Layer-35.png" "general-contractors-workers-comp-complete-coverage-guide.png"
mv "CCA-_0020_Layer-34.png" "discounts-savings-opportunities-maximizing-insurance-value.png"
mv "CCA-_0021_Layer-33.png" "hawaii-commercial-auto-insurance-roofing-companies-coverage-requirements-cost-guide-2025.png"
mv "CCA-_0022_Layer-32.png" "workers-compensation-ghost-policy-complete-guide-contractors-2025.png"
mv "CCA-_0023_Layer-31.png" "holder-certificate-construction-projects-complete-guide-2025.png"
mv "CCA-_0024_Layer-30.png" "ghost-insurance-contractors-complete-coverage-guide-2025.png"
mv "CCA-_0025_Layer-29.png" "contractor-insurance-claim-management-complete-guide-protecting-business.png"
mv "CCA-_0026_Layer-28.png" "north-carolina-contractor-insurance-guide-comprehensive-requirements-coverage-2025.png"
mv "CCA-_0027_Layer-27.png" "certificate-of-insurance-requirements-contractors.png"
mv "CCA-_0028_Layer-26.png" "professional-liability-insurance-contractors-errors-omissions-protection-2025.png"
mv "CCA-_0029_Layer-25.png" "subcontractor-insurance-requirements-complete-coverage-guide.png"
mv "CCA-_0030_Layer-24.png" "reservation-of-rights-letter-contractors-insurance-coverage-uncertain-2025.png"
mv "CCA-_0031_Layer-23.png" "pittsburgh-business-insurance-requirements-coverage-guide.png"
mv "CCA-_0032_Layer-22.png" "philadelphia-business-insurance-local-requirements-costs.png"
mv "CCA-_0033_Layer-21.png" "pa-contractor-insurance-complete-requirements-cost-guide-2025.png"
mv "CCA-_0034_Layer-20.png" "mississippi-contractor-insurance-guide-requirements-costs-coverage-options-2025.png"
mv "CCA-_0035_Layer-19.png" "mississippi-contractor-insurance-guide-requirements-costs-coverage-options-2025-alt.png"
mv "CCA-_0036_Layer-18.png" "louisiana-contractor-insurance-guide-requirements-costs-coverage-2025.png"
mv "CCA-_0037_Layer-17.png" "illinois-contractor-insurance-guide-beyond-bonds-full-coverage-2025.png"
mv "CCA-_0038_Layer-16.png" "alabama-contractor-insurance-guide-beyond-workers-comp-full-coverage-2025.png"
mv "CCA-_0039_Layer-15.png" "coi-mistakes-cost-contractors-25000-annually-avoid-7-deadly-errors.png"
mv "CCA-_0040_Layer-14.png" "wyoming-workers-compensation-roofing-contractors-complete-2025-guide.png"
mv "CCA-_0041_Layer-13.png" "montana-personal-vs-commercial-auto-insurance-roofers-need-to-know.png"
mv "CCA-_0042_Layer-12.png" "louisiana-general-liability-insurance-requirements-roofers.png"
mv "CCA-_0043_Layer-11.png" "georgia-commercial-auto-insurance-roofing-companies.png"
mv "CCA-_0044_Layer-10.png" "arkansas-roofing-contractor-license-bond-requirements-costs-2025.png"
mv "CCA-_0045_Layer-9.png" "pennsylvania-workers-comp-fund-vs-private-insurance-bankrupts-contractors.png"
mv "CCA-_0046_Layer-8.png" "new-york-personal-vs-commercial-auto-2-5-million-empire-state-compliance-trap.png"
mv "CCA-_0047_Layer-7.png" "new-york-commercial-auto-insurance-nyc-tlc-requirements-bankrupt-contractors.png"
mv "CCA-_0048_Layer-6.png" "florida-personal-vs-commercial-auto-100000-mistake-contractors-make.png"
mv "CCA-_0049_Layer-5.png" "texas-commercial-auto-insurance-mistakes-trigger-15000-dot-violations.png"
mv "CCA-_0050_Layer-4.png" "texas-personal-vs-commercial-auto-2-3-million-mistake-bankrupted-plumber.png"
mv "CCA-_0051_Layer-3.png" "florida-workers-comp-exemptions-437000-mistake-destroyed-roofing-company.png"
mv "CCA-_0052_Layer-2.png" "florida-commercial-auto-insurance-hurricane-scam-cost-contractor-4-2-million.png"
mv "CCA-_0053_Layer-1.png" "california-workers-comp-violations-cost-contractors-50000-avoid-traps.png"

echo "All files renamed successfully!"
