import { NextRequest, NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';

const WEBSITES_DIR = '/home/josh/Josh-AI/websites';

// Domain to directory mapping for websites with non-standard folder names
const DOMAIN_MAPPING: Record<string, string> = {
  'contractorschoiceagency.com': 'CCA'
};

/**
 * GET /api/websites/topical-map?domain=<domain>
 *
 * Loads processed topical map from knowledge base.
 * Returns the topical-map.json file generated by website-research-processor.
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const domain = searchParams.get('domain');

    if (!domain) {
      return NextResponse.json({ error: 'Domain parameter required' }, { status: 400 });
    }

    // Path to processed topical map JSON (with domain mapping support)
    const websiteDir = DOMAIN_MAPPING[domain] || domain;
    const topicalMapPath = path.join(
      WEBSITES_DIR,
      websiteDir,
      'ai/knowledge/04-content-strategy/ready/topical-map.json'
    );

    // Check if topical map exists
    try {
      await fs.access(topicalMapPath);
    } catch {
      return NextResponse.json({
        pillars: [],
        message: 'No topical map found. Run website-research-processor to generate it from autonomous research data.',
        hint: 'cd /home/josh/Josh-AI/tools/website-research-processor/scripts && ./process-research.sh ' + domain + ' topics'
      });
    }

    // Load and parse the topical map JSON
    const jsonContent = await fs.readFile(topicalMapPath, 'utf-8');
    const topicalMap = JSON.parse(jsonContent);

    // Return the complete topical map with metadata
    return NextResponse.json(topicalMap);

  } catch (error) {
    console.error('Error loading topical map:', error);
    return NextResponse.json(
      {
        error: 'Failed to load topical map',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
